export default [
  {
    id: 1,
    type: 1,
    bgColor: "#3b3c36",
    color: "white",
    image: "./images/animals/dog.png",
    name: "Sữa rửa mặt cho các chị em phụ nữ",
  },
  {
    id: 2,
    type: 1,
    bgColor: "#999950",
    color: "white",
    image: "./images/animals/dog1.png",
    name: "Nước rửa chén",
  },
  {
    id: 3,
    type: 1,
    bgColor: "#592321",
    color: "white",
    image: "./images/animals/dog2.png",
    name: "Thẻ cào 100k",
  },
  {
    id: 4,
    type: 1,
    bgColor: "#2c5545",
    color: "white",
    image: "./images/animals/dog3.png",
    name: "Thẻ cào 200k",
  },
  {
    id: 5,
    type: 1,
    bgColor: "#00bb2d",
    color: "white",
    image: "./images/animals/cat.png",
    name: "Thẻ cào 500k",
  },
  {
    id: 6,
    type: 1,
    bgColor: "#434b4d",
    color: "white",
    image: "./images/animals/cat1.png",
    name: "Tất chân giáng sinh",
  },
  {
    id: 7,
    type: 1,
    bgColor: "#c2b078",
    color: "white",
    image: "./images/animals/cat2.png",
    name: "Mũ bảo hiểm",
  },
  {
    id: 8,
    type: 1,
    bgColor: "#b5b8b1",
    color: "white",
    image: "./images/animals/cat3.png",
    name: "Áo chống nắngg",
  },
];
